### PR TITLE
Whitelist filter

### LINKED ISSUE #625: Enabling configuration for a conservative solver
There is a small risk that our solver might not perform well, in case a lot of tokens get suddenly added to the exchange and "unusual, unexpected" orders are being placed.

We can minimize the risk for an outage by running a conservative solver: This solver would only process orders between the tokens available in the front-end ( a conservative token set) and would try to provide reliable solutions for just them.

For this, the token filter already implemented needs to be amended such that we don't have to explicitly exclude tokens, but can just restrict the considered tokens to a list of tokens passed via an env variable.

### PR DESCRIPTION
**Pull request by josojo**
closes #625 

---
testplan: unit tests

### CODE REVIEW

File: driver/src/main.rs [hunk 1]
```diff
@@ -97,8 +100,16 @@ struct Options {
     ///     "0x7b60655Ca240AC6c76dD29c13C45BEd969Ee6F0B": "All"
     ///   }
     /// }'
-    #[structopt(long, env = "ORDERBOOK_FILTER", default_value = "{}")]
-    orderbook_filter: OrderbookFilter,
+    #[structopt(long, env = "ORDERBOOK_BLACKLIST_FILTER", default_value = "{}")]
+    blacklist_orderbook_filter: BlacklistOrderbookFilter,
+
+    /// JSON encoded object of which tokens/orders to ignore.
```
Comment (nlordell) [inline driver/src/main.rs]: nit: the comment is a little off, should be which tokens to allow.

**Review by nlordell — APPROVED** [review]
Nice!

I think having both a whitelist and a blacklist for tokens feels a little redundant. Maybe it would be better if instead of having separate filter options, the token filter options could be an enum like this:
```
pub struct OrderbookFilter {
    tokens: TokenFilter,
    users: HashMap<Address, UserOrderFilter>,
}

pub enum TokenFilter {
    Whitelist(HashSet<u16>),
    Blacklist(HashSet<u16>),
}
```

That way we can keep blacklisting users but have the ability to either whitelist or blacklist tokens. Just a suggestion, but I'm happy with how it is done how. What does everyone think?

File: driver/src/main.rs [hunk 2]
```diff
@@ -97,8 +100,16 @@ struct Options {
...
+    ///
+    /// For example: '{
+    ///   "tokens": [1, 2],
+    /// }'
+    #[structopt(long, env = "ORDERBOOK_WHITELIST_FILTER", default_value = "{}")]
```
Comment (fleupold) [inline driver/src/main.rs]: I think it would make more sense to specify a blacklist/whitelist subtype on the token in the original filter list instead of creating a new input argument.

```
enum TokenFilter {
  Whitelist(Vec<u16>),
  Blacklist(Vec<u16>),
}
```

Right now you could theoretically specify a token whitelist and a token blacklist, which doesn't really make semantic sense.

The existing orderbook_filter could look like:

```
/// For example: '{
///   "tokens": {"Whitelist": [1, 2]},
///   "users": {
///     "0x7b60655Ca240AC6c76dD29c13C45BEd969Ee6F0A": { "OrderIds": [0, 1] },
///     "0x7b60655Ca240AC6c76dD29c13C45BEd969Ee6F0B": "All"	    
///   }
```

**Review by fleupold — CHANGES_REQUESTED** [review]
Can we incorporate the distinction of black/whitelisting into the current type as having both at the same time is semantically not well defined.

File: driver/src/main.rs [hunk 3]
```diff
@@ -91,12 +91,11 @@ struct Options {
     /// JSON encoded object of which tokens/orders to ignore.
     ///
     /// For example: '{
-    ///   "tokens": [1, 2],
+    ///   "tokens": {"Whitelist": [1, 2]},
```
Comment (bh2smith) [inline driver/src/main.rs]: I guess it is not possible to provide an example that uses both a whitelist and a blacklisted token... since these are mutually exclusive.  (Perhaps we could add a comment here or somewhere stating that blacklist could be used in the same way.

File: driver/src/main.rs [hunk 4]
```diff
@@ -91,12 +91,11 @@ struct Options {
...
     ///   "users": {
     ///     "0x7b60655Ca240AC6c76dD29c13C45BEd969Ee6F0A": { "OrderIds": [0, 1] },
     ///     "0x7b60655Ca240AC6c76dD29c13C45BEd969Ee6F0B": "All"
     ///   }
-    /// }'
```
Comment (bh2smith) [inline driver/src/main.rs]: Not sure this was meant to be removed.

**Review by bh2smith — APPROVED** [review]
Cool stuff! I see someones Rust Lang skills coming along well!

File: driver/src/orderbook/filtered_orderbook.rs [hunk 5]
```diff
@@ -50,23 +62,40 @@ impl<'a> FilteredOrderbookReader<'a> {
...
+        let user_filtered_orders = token_filtered_orders
             .into_iter()
             .filter(|o| {
-                let user_filter = if let Some(user_filter) = self.filter.users.get(&o.account_id) {
+                if let Some(user_filter) = self.filter.users.get(&o.account_id) {
                     match user_filter {
-                        UserOrderFilter::All => true,
-                        UserOrderFilter::OrderIds(ids) => ids.contains(&o.id),
+                        UserOrderFilter::All => false,
+                        UserOrderFilter::OrderIds(ids) => !ids.contains(&o.id),
```
Comment (fleupold) [inline driver/src/orderbook/filtered_orderbook.rs]: Nice simplification!

**Review by fleupold — APPROVED** [review]
Really clean, really nice! Great unittests!

File: driver/src/orderbook/filtered_orderbook.rs [hunk 6]
```diff
@@ -7,12 +7,24 @@ use serde::Deserialize;
...
 
+#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
+enum TokenFilter {
+    Whitelist(HashSet<u16>),
+    Blacklist(HashSet<u16>),
+}
+
+impl Default for TokenFilter {
+    fn default() -> Self {
+        TokenFilter::Whitelist(HashSet::new())
```
Comment (nlordell) [inline driver/src/orderbook/filtered_orderbook.rs]: I think the default behaviour should be to consider all tokens (i.e. an empty black-list).

**Review by nlordell — APPROVED** [review]
Looks really good! Just one minor comment on the default behaviour.

File: driver/src/orderbook/filtered_orderbook.rs [hunk 7]
```diff
@@ -50,23 +62,40 @@ impl<'a> FilteredOrderbookReader<'a> {
 impl<'a> StableXOrderBookReading for FilteredOrderbookReader<'a> {
     fn get_auction_data(&self, index: U256) -> Result<(AccountState, Vec<Order>)> {
         let (state, orders) = self.orderbook.get_auction_data(index)?;
-        let filtered = orders
+        let token_filtered_orders = match &self.filter.tokens {
+            TokenFilter::Whitelist(token_list) => {
+                if !token_list.is_empty() {
```
[the remark this answers is not in the document]
Comment (josojo) [reply driver/src/orderbook/filtered_orderbook.rs]: You are right, I took it out.
While panicking might have made some sense, we would then also have to check that the whitelist is not just one token, etc.

**Review by bh2smith — APPROVED** [review]
