### PR TITLE
Fix naive solver panic

### LINKED ISSUE #520: Naive solver failure on mainnet
I got this panic when running the naive solver on the mainnet contract.

`env ETHEREUM_NODE_URL=https://node.mainnet.gnosisdev.com NETWORK_ID=1 PRIVATE_KEY=0000000000000000000000000000000000000000000000000000000000000001 cargo run`
```
Feb 11 10:56:19.401 INFO [driver] Using contract at 0x6f40…841f
Feb 11 10:56:19.403 INFO [driver] Using account 0x7e5f…5bdf
Feb 11 10:56:19.403 INFO [driver::util] Using naive price finder
Feb 11 10:56:19.403 INFO [driver] Orderbook filter: OrderbookFilter { tokens: {}, users: {} }
thread 'main' panicked at 'no entry found for key', src/libcore/option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::option::expect_failed
             at src/libcore/option.rs:1188
  14: core::option::Option<T>::expect
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/option.rs:348
  15: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/collections/hash/map.rs:1035
  16: <driver::price_finding::naive_solver::NaiveSolver as driver::price_finding::price_finder_interface::PriceFinding>::find_prices
             at driver/src/price_finding/naive_solver.rs:169
  17: driver::driver::stablex_driver::StableXDriver::run
             at driver/src/driver/stablex_driver.rs:65
  18: driver::main
             at driver/src/main.rs:78
  19: std::rt::lang_start::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  23: std::panicking::try
             at src/libstd/panicking.rs:270
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: std::rt::lang_start
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  27: main
  28: __libc_start_main
  29: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by e00E**
fixes #520 
Test Plan:
CI passes and added more unit tests for this issue.

### CODE REVIEW

File: driver/src/price_finding/naive_solver.rs [hunk 1]
```diff
@@ -17,16 +17,25 @@ pub enum OrderPairType {
...
 
 trait Matchable {
+    /// Returns whether the orders can be matched. For this the tokens need
+    /// to match, there must be a price that satisfies both orders and if there
+    /// is a fee then one of the tokens must be the fee token.
     fn attracts(&self, other: &Order, fee: &Option<Fee>) -> bool;
+    /// Returns whether the account to which the order belongs to has at least
+    /// as many funds of the sell token as the order's sell amount.
     fn sufficient_seller_funds(&self, state: &AccountState) -> bool;
     fn match_compare(
```
Comment (bh2smith) [inline driver/src/price_finding/naive_solver.rs]: Are we missing a doc string for this?

File: driver/src/price_finding/naive_solver.rs [hunk 2]
```diff
@@ -17,16 +17,25 @@ pub enum OrderPairType {
 }
 
 trait Matchable {
+    /// Returns whether the orders can be matched. For this the tokens need
+    /// to match, there must be a price that satisfies both orders and if there
+    /// is a fee then one of the tokens must be the fee token.
     fn attracts(&self, other: &Order, fee: &Option<Fee>) -> bool;
+    /// Returns whether the account to which the order belongs to has at least
```
Comment (bh2smith) [inline driver/src/price_finding/naive_solver.rs]:
```suggestion
    /// Returns whether the account to which the order belongs has at least
```

File: driver/src/price_finding/naive_solver.rs [hunk 3]
```diff
@@ -87,6 +96,11 @@ impl Matchable for Order {
     }
 }
 
+/// Implements PriceFinding in a simplistic way.
+///
+/// Tries to find a match of two orders that trade the fee token and uses this
+/// as the only trade in the solution.
+/// If no such match can be found then the trivial solution is used.
```
Comment (bh2smith) [inline driver/src/price_finding/naive_solver.rs]:
```suggestion
/// If no such match can be found then the trivial solution is returned.
```

File: driver/src/price_finding/naive_solver.rs [hunk 4]
```diff
@@ -108,6 +122,7 @@ impl PriceFinding for NaiveSolver {
         let mut exec_buy_amount: Vec<u128> = vec![0; orders.len()];
         let mut exec_sell_amount: Vec<u128> = vec![0; orders.len()];
 
+        let mut matching_orders_indexes: Option<(usize, usize)> = None;
```
Comment (bh2smith) [inline driver/src/price_finding/naive_solver.rs]:
```suggestion
        let mut matching_orders_indices: Option<(usize, usize)> = None;
```

File: driver/src/price_finding/naive_solver.rs [hunk 5]
```diff
@@ -145,6 +160,7 @@ impl PriceFinding for NaiveSolver {
                     }
                     None => continue,
                 }
+                matching_orders_indexes = Some((i, j));
```
Comment (bh2smith) [inline driver/src/price_finding/naive_solver.rs]: Sorry to be a pain, but I really think we should be using the term `indices` here

File: driver/src/price_finding/naive_solver.rs [hunk 6]
```diff
@@ -164,7 +180,11 @@ impl PriceFinding for NaiveSolver {
 
             // apply fee to volumes account for rounding errors, moving them to
             // the fee token
-            for (i, order) in orders.iter().enumerate() {
+            let (order_1_index, order_2_index) =
+                matching_orders_indexes.expect("fee price was nonzero so we should have a match");
+            for i in &[order_1_index, order_2_index] {
+                let i = *i;
+                let order = &orders[i];
```
Comment (bh2smith) [inline driver/src/price_finding/naive_solver.rs]: Is there something wrong with dereferencing directly inside the array access? It doesn't appear to be used more than once.

File: driver/src/price_finding/naive_solver.rs (hunk 1 above)
Comment (e00E) [reply driver/src/price_finding/naive_solver.rs]: I wasn't able to summarize this in a meaningful way in a single sentence so I skipped it. The reason I added the docstrings is that it helped me understand the code when I first read and I thought they can be useful to other people in the future. I don't think its necessary to docstring everything in this PR.

Comment (bh2smith) [reply driver/src/price_finding/naive_solver.rs]: Good enough. I totally understand!

File: driver/src/price_finding/naive_solver.rs (hunk 6 above)
Comment (e00E) [reply driver/src/price_finding/naive_solver.rs]: Nothing wrong with that but the `i` is used more than once so we would have `*i` a bunch of times and I wanted to keep the diff cleaner.

Comment (bh2smith) [reply driver/src/price_finding/naive_solver.rs]: Oh, sorry, I did no see the other usages! Cool stuff!

File: driver/src/price_finding/naive_solver.rs (hunk 5 above)
Comment (e00E) [reply driver/src/price_finding/naive_solver.rs]: No problem. I agree with using use proper grammar and spelling in the code.

File: driver/src/price_finding/naive_solver.rs [hunk 7]
```diff
@@ -108,6 +122,7 @@ impl PriceFinding for NaiveSolver {
         let mut exec_buy_amount: Vec<u128> = vec![0; orders.len()];
         let mut exec_sell_amount: Vec<u128> = vec![0; orders.len()];
 
+        let mut matching_orders_indices: Option<(usize, usize)> = None;
```
Comment (fleupold) [inline driver/src/price_finding/naive_solver.rs]: ubernit: this could be a `[usize; 2]` and slightly simplify the code where you iterate over it.

File: driver/src/price_finding/naive_solver.rs [hunk 8]
```diff
@@ -643,6 +663,92 @@ pub mod tests {
         assert!(!res.is_non_trivial());
     }
 
+    #[test]
+    fn test_match_and_lonely_order() {
```
Comment (fleupold) [inline driver/src/price_finding/naive_solver.rs]: I don't really understand what this means. Can you clarify?

File: driver/src/price_finding/naive_solver.rs [hunk 9]
```diff
@@ -164,7 +180,11 @@ impl PriceFinding for NaiveSolver {
 
             // apply fee to volumes account for rounding errors, moving them to
             // the fee token
-            for (i, order) in orders.iter().enumerate() {
+            let (order_1_index, order_2_index) =
+                matching_orders_indices.expect("fee price was nonzero so we should have a match");
+            for i in &[order_1_index, order_2_index] {
```
Comment (nlordell) [inline driver/src/price_finding/naive_solver.rs]: Is the `&` necessary? I thought arrays implemented `IntoIter` as well but I may be wrong. If it does then you wouldn’t have to dereference `i`.

**Comment by e00E** [comment]
I have added the description of the issue to the issue. Here is a copy:
The naive solver only finds one match between two orders. For this match it sets the prices in a hashmap but not for the others. The second for loop which is responsible for handling the fee then iterates over all orders, not just the two matched orders which causes a panic when the `prices` hashmap is accessed for tokens that weren't part of the match.

File: driver/src/price_finding/naive_solver.rs (hunk 8 above)
Comment (e00E) [reply driver/src/price_finding/naive_solver.rs]: There are two orders that match and then a single order that is unrelated and cannot be matched.

Comment (e00E) [reply driver/src/price_finding/naive_solver.rs]: I'll change lonely to unmatchable.

File: driver/src/price_finding/naive_solver.rs (hunk 9 above)
Comment (e00E) [reply driver/src/price_finding/naive_solver.rs]: I have to either add `&` or call `iter` manually. But either way `i` is a reference. Calling `into_iter` manually is a warning:
> warning: this method call currently resolves to `<&[T; N] as IntoIterator>::into_iter` (due to autoref coercions), but that might change in the future when `IntoIterator` impls for arrays are added.

**Comment by bh2smith** [comment]
Does this relate to our issue regarding excluding zeros from the price map and using unwrap or default?

**Comment by e00E** [comment]
I don't think so. This is exclusively about code in naive_solver.rs.
