### PR TITLE
[Driver] fix solution encoding

### LINKED ISSUE #113: [Driver] Bug on Solution Processing
### Retreth Example in Integration Test

```
truffle exec scripts/sell_order.js 0 1 2 12 12
truffle exec scripts/sell_order.js 1 2 1 2.2 2
truffle exec scripts/sell_order.js 2 0 2 150 10
truffle exec scripts/sell_order.js 3 0 1 180 15
truffle exec scripts/sell_order.js 4 1 0 4 52
truffle exec scripts/sell_order.js 5 2 0 20 280
```

Naive Solver returns (correct/expected) solution of
```
Solution { 
    surplus: 16000000000000000000000000000000000000, 
    prices: [4000000000000000000, 52000000000000000000, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 
    executed_sell_amounts: [0, 0, 0, 4000000000000000000, 52000000000000000000, 0], 
    executed_buy_amounts: [0, 0, 0, 52000000000000000000, 4000000000000000000, 0]
}
```
Which should have zipped volume vector of
```
[0, 0, 0, 0, 0, 0, 52000000000000000000, 4000000000000000000, 4000000000000000000, 52000000000000000000, 0, 0]
```
indicating that orders 1, 2, 3 and 6 have no trade volume and order 4 and 5 are matched. However zipped volume vector is
```
[0, 0, 0, 4000000000000000000, 52000000000000000000, 0, 0, 0, 0, 52000000000000000000, 4000000000000000000, 0]
```
which makes all expected balances incorrect and integration test fail.

There should also be a unit test in the driver testing that this functionality works as expected.

### PR DESCRIPTION
**Pull request by fleupold**
Closes #113 

**Test Plan**

Added unit test for solution encoding and adjusted e2e test with better documentation of what we are expecting to see.

Run both to make sure our demo is now working.

### CODE REVIEW

File: driver/src/price_finding/price_finder_interface.rs [hunk 1]
```diff
@@ -13,11 +14,13 @@ pub struct Solution {
 
 impl models::Serializable for Solution {
     fn bytes(&self) -> Vec<u8> {
-        [
-            &self.prices, 
-            &self.executed_sell_amounts,
-            &self.executed_buy_amounts,
-        ]
+        let altering_sell_buy_amounts: Vec<u128> = self.executed_buy_amounts
```
Comment (bh2smith) [inline driver/src/price_finding/price_finder_interface.rs]:
```suggestion
        let alternatinging_buy_sell_amounts: Vec<u128> = self.executed_buy_amounts
```

File: driver/src/price_finding/price_finder_interface.rs [hunk 2]
```diff
@@ -13,11 +14,13 @@ pub struct Solution {
...
+            .iter()
+            .zip(self.executed_sell_amounts.iter())
+            .flat_map(|tup| once(tup.0).chain(once(tup.1)))
+            .map(|x| x.clone())
+            .collect();
+        [&self.prices, &altering_sell_buy_amounts]
```
Comment (bh2smith) [inline driver/src/price_finding/price_finder_interface.rs]:
```suggestion
        [&self.prices, &alternating_buy_sell_amounts]
```
