### PR TITLE
Do not keep retrying to fetch token infos if call reverts

### LINKED ISSUE #1242: Don't keep retrying to fetch token info if there was a method error
There are a large number of tokens where we fail to retrieve the ERC20 info. On failure we do not cache anything so every time we update the a price source we will attempt to retrieve the info and fail. This is especially noticeable with the large number of "fake" tokens that got added today.
We should check whether the error is the result of not being able to reach the ethereum node, in which case we can retry. Or the result of an evm error. In that case it is unlikely to ever succeed so we should mark this token as failed and not attempt to retrieve it again.

### PR DESCRIPTION
**Pull request by e00E**
There are many tokens who do not implement the ERC20 standard and for
which fetching the token base info fails. In these cases it does not
make sense keep retrying. Instead we cache the error and return it back.

Fixes #1242 

### Test Plan
New unit test, manually tested that calling cache all twice does not fetch errors again on second try.

### CODE REVIEW

File: core/src/token_info/cached.rs [hunk 1]
```diff
@@ -60,14 +74,31 @@ impl TokenInfoCache {
...
+            match info {
+                Ok(info) => {
+                    self.cache
+                        .write()
+                        .await
+                        .insert(id, CacheEntry::TokenBaseInfo(info.clone()));
+                    Ok(info)
+                }
+                Err(err) if is_revert(&err) => {
+                    self.cache
```
Comment (nlordell) [inline core/src/token_info/cached.rs:94]: nit: Can we `log::debug!("{:?}")` the error here so we print the stack trace and context. Mostly because we demote the error into a `String` and lose this information.

File: core/src/token_info/cached.rs [hunk 2]
```diff
@@ -60,14 +74,31 @@ impl TokenInfoCache {
...
+                        .write()
+                        .await
+                        .insert(id, CacheEntry::UnretryableError(format!("{}", err)));
```
Comment (nlordell) [inline core/src/token_info/cached.rs:97]: ubernit: `err.to_string()`.

File: core/src/token_info/cached.rs [hunk 3]
```diff
@@ -33,7 +42,12 @@ impl TokenInfoCache {
     ) -> Self {
```
Comment (nlordell) [inline core/src/token_info/cached.rs:42]: nit: Can we have `cache: impl IntoIterator<Item = (TokenId, TokenBaseInfo)>`?

File: core/src/token_info/cached.rs [hunk 4]
```diff
@@ -60,14 +74,31 @@ impl TokenInfoCache {
 impl TokenInfoFetching for TokenInfoCache {
     fn get_token_info<'a>(&'a self, id: TokenId) -> BoxFuture<'a, Result<TokenBaseInfo>> {
         async move {
-            if let Some(info) = self.cache.read().await.get(&id).cloned() {
-                return Ok(info);
+            match self.cache.read().await.get(&id) {
+                Some(CacheEntry::TokenBaseInfo(info)) => return Ok(info.clone()),
+                Some(CacheEntry::UnretryableError(reason)) => {
+                    return Err(anyhow!("cached error: {}", reason));
```
Comment (nlordell) [inline core/src/token_info/cached.rs:80]: Maybe it makes sense to use `Context` here?
```suggestion
                    return Err(
                        anyhow!(reason)
                            .context("cached error retrieving token info"),
                    );
```

I'm also fine with not using it, just thought it was a good application for it.

**Review by nlordell — APPROVED** [review]
Looks good. I think for #1241 we can extend `CacheEntry` to also have a `Pending` variant with a `Shared<...>` future.

**Review by fleupold — APPROVED** [review]
Very nice change! Theoretically, this could also be implemented as an orthogonal `TokenInfoFetching` implementation that "filters" requests for which it has seen unretriable errors before. This would not couple it to the cache. But it's also fine the way it is.

**Comment by e00E** [comment]
> Very nice change! Theoretically, this could also be implemented as an orthogonal `TokenInfoFetching` implementation that "filters" requests for which it has seen unretriable errors before. This would not couple it to the cache. But it's also fine the way it is.

Since this is very cache related and it's overall less work to do it here I prefer this way.
