### PR TITLE
Split main into helpers

### LINKED ISSUE #831: Split main into helpers
Now that our main method handles a bunch of command line arguments, I think it would make sense if it were broken down in a few simple function calls, each of which that handles a logical component of the setup and running.

As an example breakdown, I would suggest taking each inline comment and offloading the few lines of code underneath into a method.

For example, I would call this `setup_metrics`

https://github.com/gnosis/dex-services/blob/5d496e996deca43a2e0131200fdb21464e0f4d41/driver/src/main.rs#L198-L205

### PR DESCRIPTION
**Pull request by bh2smith**
Fixes #831 

This change breaks up main into a few one-line helper functions (mostly derived from the comment above logical blocks of related code.

At this moment, we have introduced two helpers:

- `setup_metrics`
- `setup_http_services`

Not yet sure if there are other things that can be broken out.

### Test Plan
CI should suffice in detecting whether these changes correspond to equivalent code.

### CODE REVIEW

File: driver/src/main.rs [hunk 1]
```diff
@@ -293,6 +274,38 @@ fn main() {
...
+        metric_server.serve(9586);
+    });
+
+    (stablex_metrics, http_metrics)
+}
+
+fn setup_http_services(
+    http_factory: HttpFactory,
+    options: Options,
+) -> (Web3, GnosisSafeGasStation, PriceOracle) {
```
Comment (e00E) [inline driver/src/main.rs:292]: Nit: To me it is cleaner to take `Options` by reference `&Options` and then clone the fields you do need owned inside of the function. That way we don't have to clone the whole thing. But this code is fine too so if you prefer this then feel free not to change it.

Comment (bh2smith) [reply driver/src/main.rs:292]: Nah, I don't prefer and simply wasn't aware how to actually do this. Thanks for your meaningful and surely better suggested approach.

File: driver/src/driver/scheduler.rs [hunk 2]
```diff
@@ -71,7 +71,7 @@ impl Default for AuctionTimingConfiguration {
 }
 
 /// The different kinds of schedulers.
-#[derive(Debug)]
+#[derive(Clone, Debug)]
```
Comment (fleupold) [inline driver/src/driver/scheduler.rs:74]: nit: do you still need these here and below?

**Comment by fleupold** [comment]
Ah I guess this PR is still in draft mode. What's missing for it to be ready for review?

File: driver/src/orderbook/mod.rs [hunk 3]
```diff
@@ -39,7 +39,7 @@ pub trait StableXOrderBookReading {
 }
 
 /// The different kinds of orderbook readers.
-#[derive(Debug)]
+#[derive(Clone, Debug)]
```
Comment (nlordell) [inline driver/src/orderbook/mod.rs:42]: This can probably be `Copy` as well so you don't need an explicit call to `Clone`
```suggestion
#[derive(Copy, Clone, Debug)]
```

File: driver/src/main.rs [hunk 4]
```diff
@@ -44,7 +44,7 @@ use std::time::Duration;
 use structopt::StructOpt;
 use url::Url;
 
-#[derive(Debug, StructOpt)]
+#[derive(Clone, Debug, StructOpt)]
```
Comment (nlordell) [inline driver/src/main.rs:47]: nit: I don't think `options.clone()` is being used anywhere so its probably not needed here.

File: driver/src/driver/scheduler.rs (hunk 2 above)
Comment (bh2smith) [reply driver/src/driver/scheduler.rs:74]: Yes, I believe I do.

File: driver/src/main.rs (hunk 4 above)
Comment (bh2smith) [reply driver/src/main.rs:47]:
```suggestion
#[derive(Debug, StructOpt)]
```

File: driver/src/driver/scheduler.rs (hunk 2 above)
Comment (bh2smith) [reply driver/src/driver/scheduler.rs:74]:
```suggestion
#[derive(Debug)]
```

File: driver/src/orderbook/mod.rs (hunk 3 above)
Comment (bh2smith) [reply driver/src/orderbook/mod.rs:42]: I'll give it a try.

Comment (bh2smith) [reply driver/src/orderbook/mod.rs:42]: You mean on `OrderbookReaderKind`? Should I also be removing the clone? What is this? I don't even explicitly clone this anywhere.

**Comment by bh2smith** [comment]
For some reason, this update with master branch is failing to fetch some archives. I am certain that this is not related to the changes here, but it is blocking the merge.

```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/k/keyutils/libkeyutils1_1.5.9-9.2ubuntu2_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libroken18-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libasn1-8-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libheimbase1-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libhcrypto4-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libwind0-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libhx509-5-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libkrb5-26-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libheimntlm0-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libgssapi3-heimdal_7.5.0+dfsg-1_amd64.deb  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update   && apt-get install -y --no-install-recommends libpq-dev libssl1.0.0 libssl-dev ca-certificates   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

The command "docker build --tag stablex-binary-private --build-arg SOLVER_BASE=163030813197.dkr.ecr.eu-central-1.amazonaws.com/dex-solver:v0.6.4 --build-arg RUST_BASE=rust-binary -f docker/rust/Dockerfile ." exited with 100.
```


Has anyone else from @gnosis/dex-services experienced this in the past?
