### PR TITLE
Retry with increased gas price

### LINKED ISSUE #677: Submit Solution: Retry with increased gas price
The likely cause of the following failed transaction is that the gas price was not high enough to get this transaction processed in time.

https://etherscan.io/tx/0xc87c495f1d05203d4d1a48ba785a883e506c4cadd64ea8d88e9e70b4175f53e1

A reasonable fix here is to observe that the transaction is taking too long and increase the gas price to avoid the dreadful error "Solutions are no longer accepted for this batch".

An incremental solution proposed by @fleupold is to double the gas prices up to a maximum bound.

### PR DESCRIPTION
**Pull request by bh2smith**
This PR introduces a few fundamental changes to `StableXContract.submit_solution` so to have a natural implementation of `retry_with_increased_gas_price` that is easily testable.

- `GasStation` is moved into the `SolutionSubmitter` instead of `StableXContract`
- Introduce a new function `retry_with_gas_price_increase` which doubles the gas price if solution is not mined within one block (to a maximum cap of 60 GWei).
- This functionality is tested with one test showing the gas price incremented (to the cap) and another which persists in not being mined. 

Note that the initial gas estimate cannot exceed the cap and that the the block timeout is reset to default on the last submitted transaction.

Closes #677

**TestPlan** Unit tests.

### CODE REVIEW

File: driver/src/contracts/stablex_contract.rs [hunk 1]
```diff
@@ -93,10 +85,12 @@ pub trait StableXContract {
         batch_index: U256,
         solution: Solution,
         claimed_objective_value: U256,
-    ) -> Result<()>;
+        gas_price: U256,
+        timeout: Option<usize>,
```
Comment (e00E) [inline driver/src/contracts/stablex_contract.rs:89]: Either explain in a comment or rename the variable so that the unit of the timeout is clear.

File: driver/src/solution_submission/mod.rs [hunk 2]
```diff
@@ -120,48 +128,189 @@ impl<'a> StableXSolutionSubmitting for StableXSolutionSubmitter<'a> {
...
+            solution.clone(),
+            claimed_objective_value,
+            self.gas_price_estimating,
+            60_000_000_000u64.into(),
+        )
+        .map_err(|err| {
+            extract_transaction_receipt(&err)
+                .and_then(|tx| {
+                    let block_number = tx.block_number?;
+                    match self.contract.get_solution_objective_value(
```
Comment (e00E) [inline driver/src/solution_submission/mod.rs:143]: What is the purpose of this?

File: driver/src/solution_submission/mod.rs [hunk 3]
```diff
@@ -120,48 +128,189 @@ impl<'a> StableXSolutionSubmitting for StableXSolutionSubmitter<'a> {
...
+            } else {
+                Some(BLOCK_TIMEOUT)
+            },
+        );
+        // Breaking condition for our loop
+        gas_price < gas_cap
+            && matches!(
+                result,
+                Err(MethodError {
+                    inner: ExecutionError::ConfirmTimeout,
```
Comment (e00E) [inline driver/src/solution_submission/mod.rs:203]: It might be useful to log this, at least in the beginning. I'm afraid we might unexpectedly always get a timeout when using `block_timeout == 1` or something unexpected like that.

**Review by e00E — APPROVED** [review]

File: driver/src/solution_submission/mod.rs (hunk 2 above)
Comment (nlordell) [reply driver/src/solution_submission/mod.rs:143]: This was there before, the diff is just struggling to show it correctly. It was used to get the revert message in case of a transaction failure.

**Comment by nlordell** [comment]
@bh2smith Commandeering this since you will be traveling

File: driver/src/solution_submission/mod.rs [hunk 4]
```diff
@@ -120,48 +128,193 @@ impl<'a> StableXSolutionSubmitting for StableXSolutionSubmitter<'a> {
...
+fn retry_with_gas_price_increase(
+    contract: &dyn StableXContract,
+    batch_index: U256,
+    solution: Solution,
+    claimed_objective_value: U256,
+    gas_price_estimating: &dyn GasPriceEstimating,
+    gas_cap: U256,
+) -> Result<(), MethodError> {
+    const INCREASE_FACTOR: u32 = 2;
+    const BLOCK_TIMEOUT: usize = 1;
```
Comment (fleupold) [inline driver/src/solution_submission/mod.rs:167]: Isn't 1 block timeout a bit too aggressive? I'm worried that our tx might not yet even have broadcasted until the next block is mined. Maybe we can start with 2?

In the future it would also be good if this could be a function of time remaining as with e.g. 3 minutes or so we could event try the normal safe estimate first in oder to save gas.

File: driver/src/solution_submission/mod.rs [hunk 5]
```diff
@@ -120,48 +128,193 @@ impl<'a> StableXSolutionSubmitting for StableXSolutionSubmitter<'a> {
...
+    const DEFAULT_GAS_PRICE: u64 = 15_000_000_000;
+
+    let mut gas_price = match gas_price_estimating.estimate_gas_price() {
```
Comment (fleupold) [inline driver/src/solution_submission/mod.rs:170]: Do you have any thoughts if this be done as well inside each loop in case the gas price changed in the meantime?

**Review by fleupold — APPROVED** [review]
Looks great ⛽📈 

Generally, we could also abstract gas_estimation into a strategy object that can act based on the time remaining and maybe on the time tried before if we feel it becomes too much logic to keep it inlined in this module.

File: driver/src/solution_submission/mod.rs (hunk 4 above)
Comment (nlordell) [reply driver/src/solution_submission/mod.rs:167]: I had talked to @bh2smith and if mainnet transactions get mined pretty far apart. We figured that if the block timeout were 2 we wouldn't really retry more than once.

I can bump this up to 2 and if we realize the transaction isn't really getting re-sent than we can try for a different strategy (like one where timeout is in function of time remaining).

File: driver/src/solution_submission/mod.rs (hunk 5 above)
Comment (nlordell) [reply driver/src/solution_submission/mod.rs:170]: Do you think the gas price could double in 2 blocks?

Comment (nlordell) [reply driver/src/solution_submission/mod.rs:170]: I implemented this, which I guess will help when the gas price is increasing rapidly

Comment (bh2smith) [reply driver/src/solution_submission/mod.rs]: Unfortunately I didn't catch this at the time. I meant to only make the estimation once. Not exactly sure how this slipped by.

Comment (bh2smith) [reply driver/src/solution_submission/mod.rs]: Oh, I see this was introduced in the last commit. I think it would be best if we only estimate once and increase from our current estimate.
